### ISSUE TITLE
Prototype UI/UX Workflow Tweaks

### ISSUE THREAD

**Issue by klappy** [Bridgeconn/translationManager#100]
### Progress Screen
- [ ] Make First column with labels to be smaller and consistent for all rows.
- [ ] Add Total Chapters for row headers, one for each book
- [ ] Add Completed chapters number for each milestone above progress bars.
- [ ] Move Percentage number for each milestone to below each progress bar.

### Milestone Screen
- [ ] Remove Project selection

### Team Screen
- [ ] Remove Project selection

### Assign Screen
- [ ] Reorder: Project, Book, Chapter, Milestone, Team
- [ ] Fix Status button to just be a checkbox and not require lots of clicking and pressing enter.
